ExpenseTracker2/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExpenseTracker2.Models;

namespace ExpenseTracker2.Controllers
{
    public class ExpenseController : Controller
    {
        DatabaseCon con = new DatabaseCon();
        // GET: Expense
        public ActionResult Index(int? cat)
        {
            if (cat != null)
            {
                var catlist = con.eobj.Where(x => x.catId == cat).ToList();
                return View(catlist);

            }
            else
            {
                var catlist = con.eobj.ToList();
                return View(catlist);
            }
           
        }   
          
        [HttpGet]
        public ActionResult Create(long? ID)
        {
            if (ID == null)
            {
                var catlist = con.cobj.ToList();
                ViewBag.catId = new SelectList(catlist, "catId", "catName");
                return View(new Expense());
            }
            else
            {
                var catlist = con.cobj.ToList();
                ViewBag.catId = new SelectList(catlist, "catId", "catName");
                return View(con.eobj.ToList().Find(e => e.exId == ID.Value));
            }
           
        }
        
        [HttpPost]
        public ActionResult Create(Expense e)
        {
            string btnaction = Request.Params["btn"].ToString();
            float total_exp = con.eobj.Where(j => j.catId == e.catId).ToList().Sum(j => j.Amount);
            Category c = con.cobj.FirstOrDefault(j => j.catId == e.catId);
            total_exp += e.Amount;
        
            if (total_exp > c.catExpLimit)
            {
               TempData["AlertMsg"] = "Edit Expense limit...";
                
                return RedirectToAction("ListofCategory","Home");

            }
            else
            {
                if (ModelState.IsValid)
                {
                    if (e.exId == 0)
                    {

                        var catlist = con.cobj.ToList();
                        ViewBag.catId = new SelectList(catlist, "catId", "catName");
                        con.eobj.Add(e);
                        con.SaveChanges();
                        ModelState.Clear();
                        e = new Expense();
                        TempData["AlertMsg"] = "Record Inserted...";
                        return RedirectToAction("ExpenseList");
                    }
                    else
                    {
                        var catlist = con.cobj.ToList();
                        ViewBag.catId = new SelectList(catlist, "catId", "catName");

                        con.Entry(e).State = System.Data.Entity.EntityState.Modified;
                        con.SaveChanges();
                        TempData["AlertMsg"] = "Record Updated...";
                        return RedirectToAction("ExpenseList");
                    }

                }
                return View(e);
            }
        }
        public ActionResult ExpenseList()
        {
            return View(con.eobj.ToList());
        }
        public ActionResult Delete(long? ID)
        {
            if (ID == null)
            {
                return View(new Expense());
            }
            else
            {
                Expense e = con.eobj.ToList().Find(j => j.exId == ID.Value);
                con.Entry(e).State = System.Data.Entity.EntityState.Deleted;
                con.SaveChanges();
                 TempData["AlertMsg"] = "Record Deleted...";
                return RedirectToAction("ExpenseList");

            }

        }
        public ActionResult TotalExpense()
        {
            ViewBag.exp = con.eobj.Sum(h => h.Amount);
            return View(ViewBag.exp);
        }
       


    }

}

ExpenseTracker2/Controllers/TotalLimitController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExpenseTracker2.Models;
namespace ExpenseTracker2.Controllers
{
    public class TotalLimitController : Controller
    {
        DatabaseCon con = new DatabaseCon();
        // GET: TotalLimit
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult AddLimit()
        {
            Limit l = new Limit();
            l.totLimit = 40000.0f;
            con.lobj.Add(l);
            con.SaveChanges();
            return RedirectToAction("ListTotLimit");
            

           
        }
        [HttpPost]
        public ActionResult AddLimit(Limit l)
        {
            
            
            return View(l);
        }
        [HttpGet]
        public ActionResult EditLimit(int id)
        {
            var row = con.lobj.Where(h => h.Id == id).FirstOrDefault();
            return View(row);

        }
        [HttpPost]
        public ActionResult EditLimit(Limit l)
        {
            
            if (ModelState.IsValid)
            {
                l.Id = l.Id;
                l.totLimit = l.totLimit;
               

                con.Entry(l).State = EntityState.Modified;
                con.SaveChanges();
                TempData["AlertMsg"] = "Record Updated Successful...";

                return RedirectToAction("ListTotLimit");
            }
            ModelState.Clear();
            return View("AddLimit");
            // var row = Db_Conn.Model_Category.Where(h => h.Id == id).FirstOrDefault();
        }


        public ActionResult ListTotLimit()
        {
            return View(con.lobj.Where(h => h.Id == 1).ToList());
        }
       

    }
}

ExpenseTracker2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Expense Tracker | Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/BackEnd/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/BackEnd/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/BackEnd/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/BackEnd/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/BackEnd/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/BackEnd/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/BackEnd/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/BackEnd/plugins/summernote/summernote-bs4.min.css">
    <link rel="stylesheet" href="~/Content/bootstrap-datetimepicker.min.css">
   <script src="~/Scripts/jquery-3.3.1.min.js"></script>
  

    
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
        </div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Home</a>
                </li>
               
            <!-- Right navbar links -->
            
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="dist/img/AdminLTELogo.png" alt="" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Expense Tracker</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    @*<div class="image">
                        <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>*@
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        <li class="menu-open @(ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "nav-link active" : "")">
                            <a href="@Url.Action("Index","Home")" class="nav-link clr">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p style="margin-left:10px;">
                                    Dashboard

                                </p>
                            </a>

                        </li>
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "ListofCategory" ? "nav-link active" : "")">
                            <a href="@Url.Action("ListofCategory","Home")" class="nav-link">
                                <i class="fas fa-list"> </i>
                                <p style="margin-left:10px;">
                                    List of Category
                                </p>


                            </a>
                            
                        </li>
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "ExpenseList" ? "nav-link active" : "")">
                            <a href="@Url.Action("ExpenseList","Expense")" class="nav-link">
                                <i class="fas fa-file-invoice-dollar"></i>
                                <p style="margin-left:10px;">
                                    List of Expenses
                                </p>
                            </a>
                           
                        </li>
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "TotalExpense" ? "nav-link active" : "")">
                            <a href="@Url.Action("TotalExpense","Expense")" class="nav-link">
                                <i class="fas fa-calculator"></i>
                                <p style="margin-left:10px;">
                                    Total Expense
                                </p>
                            </a>
                            
                        </li>
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "AddLimit" ? "nav-link active" : "")">
                            <a href="@Url.Action("AddLimit","TotalLimit")" class="nav-link clr">
                                <i class="fas fa-calculator"></i>
                                <p style="margin-left:10px;">
                                    Total Expense Limit
                                </p>
                            </a>
                       
                        </li>    
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">

                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">Dashboard</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Dashboard</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">

                    @RenderBody()
                    <!-- /.row (main row) -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2023-24 <a href="https://thegatewaycorp.com">thegatewaycorp.com</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Expense</b> Tracker
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/BackEnd/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/BackEnd/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    @*<script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>*@
    <!-- Bootstrap 4 -->
    <!-- JQVMap -->
    <script src="~/BackEnd/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/BackEnd/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/BackEnd/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/BackEnd/plugins/moment/moment.min.js"></script>
    <script src="~/BackEnd/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/BackEnd/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/BackEnd/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/BackEnd/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/BackEnd/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/BackEnd/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/BackEnd/dist/js/pages/dashboard.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/CustomScript.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>